title: Coin Hunter Adventure Pixel
description: ピクセルアートスタイルのコイン収集アドベンチャーゲーム
theme: jekyll-theme-minimal
lang: ja

# GitHub Pages設定
repository: becky3/coin-hunter-adventure-pixel
baseurl: ""
url: "https://becky3.github.io/coin-hunter-adventure-pixel"

# ナビゲーション
navigation:
  - title: ホーム
    url: /
  - title: はじめに
    url: /getting-started/
  - title: 開発者向け
    url: /development/
  - title: 仕様書
    url: /specifications/
  - title: リソース
    url: /resources/

# プラグイン
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/